apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pgqh552gp-nodejs 
  janus-idp.io/tekton: pgqh552gp-nodejs
  backstage.io/kubernetes-id: pgqh552gp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pgqh552gp-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  